
server:
  port:  ${PORT:0}
#  servlet:
#    context-path: /order-service

spring:
  application:
    name: order-service

  datasource:
    name: beer-shop-datasource
    url: 'jdbc:postgresql://localhost:5432/beer_order_service'
    username: postgres
    password: ENC(j7OC/L6FZI+8d29tRAYsreDkvGb+V/XF)
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
#    enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  # credentials for this docker image - vromero/activemq-artemis
  artemis:
    user: admin
    password: ENC(j7OC/L6FZI+8d29tRAYsreDkvGb+V/XF)
#  flyway:
#    enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true

jasypt:
  encryptor:
    password: helw4345gr@%#5fgddlo@1

sfg:
  brewery:
    beer-service-host: http://localhost:8080

# Enable logging for config troubleshooting
logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com: DEBUG
      springboot:
        storedprocedure: DEBUG
      zaxxer:
        hikari:
          HikariConfig: DEBUG

